# Ignore certain URLs or patterns
exclude = [
    "localhost",           # Ignore localhost links
    "example.com",         # Ignore example domains
    "http://127.0.0.1"     # Ignore local IP links
]

# Retry failed links before reporting
retry = 3

# Timeout for links (in seconds)
timeout = 10

# Acceptable status codes
accept = [200, 403]

# Maximum concurrency for checking links
max_concurrency = 10
