name: Feature Request
description: Propose a new capability or improvement
title: "[feat]: <short summary>"
labels: ["enhancement", "triage"]
assignees:
  - flare-foundation/developer-hub-team
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Use case
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the change (API/UX/config/etc.)
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any additional information that could be useful, like screenshots etc.
    validations:
      required: false
