name: New Feed Request
description: Request a new feed to be added to FTSO
title: "[req]: <BASE/QUOTE>"
labels: ["enhancement", "ftso"]
assignees:
  - dineshpinto
body:
  - type: input
    id: pair
    attributes:
      label: Feed Name
      placeholder: "FLR/USD"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Justification
      description: Clear and concise explanation of why you are requesting this feed
    validations:
      required: true

  - type: textarea
    id: venues
    attributes:
      label: Trading Venues (CeX/DeX/Aggregators)
      description: Include tickers/symbols per venue
      value: |
        - Coinbase: FLR/USD
        - Bybit: FLR/USDT
        - SparkDEX: FLR/USDT0
      render: markdown
    validations:
      required: true

  - type: dropdown
    id: liquidity
    attributes:
      label: Liquidity & Volume (avg daily)
      options: ["<$1M", "$1-10M", "$10-100M", ">$100M"]
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Contact (Email or Discord/Telegram)
    validations:
      required: true
