name: Web2Json API key request
description: Request an API key for a FDC Web2Json source
title: "[req]: <sourceId> on <network>"
labels: ["enhancement", "fdc"]
assignees:
  - nikerzetic-aflabs
  - jO-Osko
body:
  - type: dropdown
    id: network
    attributes:
      label: Network
      options:
        - Flare Mainnet
        - Songbird Canary-Network
    validations:
      required: true
  - type: input
    id: sourceId
    attributes:
      label: Web2Json sourceId
      placeholder: "Ignite"
    validations:
      required: true
  - type: input
    id: providerAddress
    attributes:
      label: Identity address of provider
    validations:
      required: true
