name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build website with LLMs generation
        run: npm run build:llms-fixed
      - name: Verify LLMs files
        run: |
          echo "Verifying LLMs files generation..."
          
          # Check if LLMs files were generated
          if [ ! -f "build/llms.txt" ] || [ ! -f "build/llms-full.txt" ]; then
            echo "❌ LLMs files not found!"
            exit 1
          fi
          
          # Check file sizes
          llms_txt_size=$(wc -c < build/llms.txt)
          llms_full_size=$(wc -c < build/llms-full.txt)
          echo "llms.txt: $llms_txt_size bytes"
          echo "llms-full.txt: $llms_full_size bytes"
          
          # Verify URLs are correct (no prepended numbers)
          if grep -q "https://dev\.flare\.network/docs/[^)]*/\d+-" build/llms.txt; then
            echo "❌ Found URLs with prepended numbers!"
            exit 1
          else
            echo "✅ All URLs are correctly formatted"
          fi
          
          # Check content structure
          sections=$(grep -c "^- \[" build/llms.txt || true)
          echo "Found $sections sections in llms.txt"
          
          if [ "$sections" -lt 10 ]; then
            echo "❌ Too few sections found!"
            exit 1
          fi
          
          echo "✅ LLMs files verified successfully"
      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
