name: Check External Links

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-external-links:
    name: Check External Links
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run External Link Checks
        run: npm run linkcheck-external
