name: Lint and Check Links

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Lint and Check Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint with ESLint
        run: npm run lint

      - name: Build website
        run: npm run build

      - name: Prettier Code
        run: npm run format:diff

      - name: Check types
        run: npm run typecheck

      # Run Link Checker using Lychee Action
      - name: Check for Broken Links
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          # Specify files to scan for links
          args: >
            --accept 200,403
            --no-progress
            '**/*.md' '**/*.mdx' '**/*.html'
          # Path to Lychee configuration file
          config-file: .github/config/lychee.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Report Failure on Broken Links
      - name: Report Failure on Broken Links
        if: failure()
        run: |
          echo "::error:: Broken links detected. Please fix them before merging."
