name: Lint and Check Links

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Lint and Check Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint with ESLint
        run: npm run lint

      - name: Build website
        run: npm run build

      - name: Prettier Code
        run: npm run format:diff

      - name: Check types
        run: npm run typecheck

      # Install Lychee for link checking
      - name: Install Lychee (Link Checker)
        run: |
          wget -q https://github.com/lycheeverse/lychee/releases/latest/download/lychee-linux-x86_64.tar.gz
          tar -xzf lychee-linux-x86_64.tar.gz
          sudo mv lychee /usr/local/bin/

      # Run Link Checker
      - name: Run Link Checker
        run: |
          lychee \
            --config .github/config/lychee.toml \
            --accept=200,403 \
            --no-progress \
            '**/*.md' '**/*.mdx' '**/*.html'

      # Report Failure on Broken Links
      - name: Report Failure on Broken Links
        if: failure()
        run: |
          echo "::error:: Broken links detected. Please fix them before merging."
