name: Spell Check

on:
  pull_request:
    paths:
      - "**/*.md"
      - "**/*.mdx"
      - "**/*.txt"
      - "**/*.yml"
      - "**/*.yaml"
      - "**/*.py"
      - "**/*.js"
      - "**/*.ts"
      - "**/*.html"
      - "**/*.rst"
      - "!**/*.svg" # Exclude svg files from triggering the workflow
      - "!**/*.sol"
      - "**/*.go"
      - "!**/*.sum"
      - "!**/*.mod"

jobs:
  spell-check:
    if: github.event.pull_request.changed_files > 0
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install codespell
        run: pip install codespell

      - name: Run Spell Check
        run: |
          codespell \
            --ignore-words=.github/config/ignored-words.txt \
            --skip="*.svg,*.png,*.jpg,*.woff,*.woff2,*.pdf,*.json,package-lock.json" \
            --quiet-level=2 \
            --check-filenames \
            .

      - name: Annotate spelling errors
        if: failure()
        run: echo "::error::Spelling errors detected. Please fix the typos or add to the ignore list if intentional."
