name: Spell Check
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: ["**/*.md", "**/*.mdx", ".github/workflows/spell-check.yml"]

permissions:
  contents: read

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get changed markdown files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          base_sha: ${{ github.event.pull_request.base.sha }}
          sha: ${{ github.event.pull_request.head.sha }}
          include_all_old_new_renamed_files: true
          files: |
            **/*.md
            **/*.mdx

      - name: Run spell check
        uses: crate-ci/typos@v1
        with:
          config: ./.github/config/typos.toml
          files: ${{ steps.changed-files.outputs.all_changed_files }}
