name: Spell Check

on:
  pull_request:
    paths:
      - "**/*.md"
      - "**/*.mdx"
      - "**/*.txt"
      - "**/*.yml"
      - "**/*.yaml"
      - "**/*.py"
      - "**/*.js"
      - "**/*.ts"
      - "**/*.html"
      - "**/*.rst"
      - "**/*.go"
      - "!**/*.svg" # Exclude svg files from triggering the workflow
      - "!**/*.sum"
      - "!**/*.mod"

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Changed Files
        id: changed-files
        run: |
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            echo "First push or fork detected. Checking all files."
            git ls-files > changed-files.txt
          else
            git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed-files.txt
          fi
          grep -E '\.(md|mdx|txt|yml|yaml|py|js|ts|html|rst|go)$' changed-files.txt || echo "No files to check" && exit 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install codespell
        run: pip install codespell

      - name: Run Spell Check
        run: |
          codespell \
            --ignore-words=.github/config/ignored-words.txt \
            --skip="*.svg,*.png,*.jpg,*.woff,*.woff2,*.pdf,*.json,package-lock.json" \
            --quiet-level=2 \
            --check-filenames \
            .

      - name: Annotate Spelling Errors
        if: failure()
        run: |
          echo "::error:: Spelling errors detected. Please fix the typos or add to the ignore list if intentional."
