name: Spell Check
on:
  pull_request:

permissions:
  contents: read

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full git history to ensure we get all files

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          include_all_old_new_renamed_files: true # Include renamed files
          files: |
            **/*.md
            **/*.mdx

      - name: Run Spell Check on all changed files
        uses: crate-ci/typos@master
        with:
          config: ./.github/config/typos.toml
          files: ${{ steps.changed-files.outputs.all_changed_files }}
