name: Test JavaScript Examples

on:
  pull_request:
    branches:
      - main
    paths:
      - "examples/developer-hub-javascript/**"
      - ".github/workflows/test-javascript-examples.yml"

permissions:
  contents: read

jobs:
  test:
    name: Test JavaScript Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
      - uses: pnpm/action-setup@v4
        with:
          cache: "true"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Format with prettier
        run: pnpm --filter ./examples/developer-hub-javascript run format:check
      - name: Lint with ESLint
        run: pnpm --filter ./examples/developer-hub-javascript run lint:check
      - name: Test with jest
        run: pnpm --filter ./examples/developer-hub-javascript run test
